# Generated by Django 2.0.1 on 2018-01-09 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_data', models.DateTimeField()),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('RESERVED', 'RESERVED'), ('CANCELLED', 'CANCELLED')], max_length=20)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Property')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Renter')),
            ],
            options={
                'verbose_name': 'Reservations',
                'verbose_name_plural': 'Reservations',
            },
        ),
    ]
